### ISSUE TITLE
feature: create gitter/discord or a like to colaborate

### ISSUE THREAD

**Issue by regevbr** [PruvoNet/node-upgrade-checker#23]

**Comment by ynahmany** [comment]
Created:
[https://gitter.im/node-upgrade-checker/community](url)

**Comment by regevbr** [comment]
cool, can we also have a private room there?

**Comment by ynahmany** [comment]
yes, you can invite collaborators to discuss privately. 
Also, a cool feature, we can integrate GitHub, action ci and so on really easy. 
will do it once we will create an organization.

**Comment by regevbr** [comment]
Cool!
Can we close the ticket?

**Comment by regevbr** [comment]
we decided on discord - https://discord.gg/P28NWr
